<!DOCTYPE html>
<html>
    <title>MYPLS</title>

    <head>
         <link rel="stylesheet" href="CSS/index_styles.css">

    </head>
    <body>

    <div>


         <form method="GET" action="/registration">
             <input type="submit" value="Register as a New User" />
         </form>
         <form method="GET" action="/login">
                      <input type="submit" value="login" />
            </form>
    </div>

    </body>
</html>